/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // 既存のデータを削除
  await knex("lesson").del();

  // 初期データを挿入
  await knex("lesson").insert([
    {
      id: 1,
      store_id: 1,
      date: "2024-12-01",
      start_time: "10:00:00",
      end_time: "12:00:00",
      location: "関東",
      description: "初心者向けヨガレッスン",
      imagePath: "/images/lesson1.jpg",
      moviePath: "/movies/lesson1.mp4",
      review: 5,
      indicator: 85.0,
      momentum: 100,
    },
    {
      id: 2,
      store_id: 2,
      date: "2024-12-02",
      start_time: "14:00:00",
      end_time: "15:30:00",
      location: "関西",
      description: "中級者向けピラティス",
      imagePath: "/images/lesson2.jpg",
      moviePath: "/movies/lesson2.mp4",
      review: null,
      indicator: 78.5,
      momentum: 75,
    },
    {
      id: 3,
      store_id: 1,
      date: "2024-12-03",
      start_time: "18:00:00",
      end_time: "20:00:00",
      location: "関東",
      description: "上級者向けヨガレッスン",
      imagePath: "/images/lesson3.jpg",
      moviePath: "/movies/lesson3.mp4",
      review: 4,
      indicator: 92.1,
      momentum: null,
    },
    {
      id: 4,
      store_id: 2,
      date: "2024-12-04",
      start_time: "09:00:00",
      end_time: "10:30:00",
      location: "関西",
      description: "モーニングストレッチ",
      imagePath: "/images/lesson4.jpg",
      moviePath: "/movies/lesson4.mp4",
      review: 3,
      indicator: 70.2,
      momentum: 60,
    },
    {
      id: 5,
      store_id: 3,
      date: "2024-12-05",
      start_time: "11:00:00",
      end_time: "12:30:00",
      location: "関西",
      description: "初心者向けリラクゼーションヨガ",
      imagePath: "/images/lesson5.jpg",
      moviePath: "/movies/lesson5.mp4",
      review: 5,
      indicator: 88.7,
      momentum: 120,
    },
    {
      id: 6,
      store_id: 1,
      date: "2024-12-06",
      start_time: "16:00:00",
      end_time: "18:00:00",
      location: "関西",
      description: "筋力アップのためのヨガ",
      imagePath: "/images/lesson6.jpg",
      moviePath: "/movies/lesson6.mp4",
      review: 4,
      indicator: 80.5,
      momentum: 90,
    },
    {
      id: 7,
      store_id: 2,
      date: "2024-12-07",
      start_time: "14:00:00",
      end_time: "15:30:00",
      location: "関西",
      description: "ピラティス初級レッスン",
      imagePath: "/images/lesson7.jpg",
      moviePath: "/movies/lesson7.mp4",
      review: 3,
      indicator: 68.4,
      momentum: 50,
    },
    {
      id: 8,
      store_id: 3,
      date: "2024-12-08",
      start_time: "10:00:00",
      end_time: "11:30:00",
      location: "関西",
      description: "リフレッシュヨガ",
      imagePath: "/images/lesson8.jpg",
      moviePath: "/movies/lesson8.mp4",
      review: null,
      indicator: 75.3,
      momentum: 70,
    },
    {
      id: 9,
      store_id: 1,
      date: "2024-12-09",
      start_time: "18:00:00",
      end_time: "20:00:00",
      location: "関東",
      description: "ナイトヨガ",
      imagePath: "/images/lesson9.jpg",
      moviePath: "/movies/lesson9.mp4",
      review: 4,
      indicator: 88.0,
      momentum: null,
    },
    {
      id: 10,
      store_id: 2,
      date: "2024-12-10",
      start_time: "10:00:00",
      end_time: "11:30:00",
      location: "関西",
      description: "初心者向け太極拳",
      imagePath: "/images/lesson10.jpg",
      moviePath: "/movies/lesson10.mp4",
      review: 5,
      indicator: 85.6,
      momentum: 95,
    },
    // 以下、さらに 10 個のサンプルを続けます
    {
      id: 11,
      store_id: 3,
      date: "2024-12-11",
      start_time: "13:00:00",
      end_time: "14:30:00",
      location: "関西",
      description: "リラックス瞑想",
      imagePath: "/images/lesson11.jpg",
      moviePath: "/movies/lesson11.mp4",
      review: null,
      indicator: 70.0,
      momentum: 40,
    },
    {
      id: 12,
      store_id: 1,
      date: "2024-12-12",
      start_time: "15:00:00",
      end_time: "16:30:00",
      location: "関東",
      description: "上級ヨガクラス",
      imagePath: "/images/lesson12.jpg",
      moviePath: "/movies/lesson12.mp4",
      review: 5,
      indicator: 90.0,
      momentum: 100,
    },
    {
      id: 13,
      store_id: 2,
      date: "2024-12-13",
      start_time: "09:00:00",
      end_time: "10:30:00",
      location: "関西",
      description: "早朝ピラティス",
      imagePath: "/images/lesson13.jpg",
      moviePath: "/movies/lesson13.mp4",
      review: 4,
      indicator: 78.2,
      momentum: 60,
    },
    {
      id: 14,
      store_id: 1,
      date: "2024-12-14",
      start_time: "16:00:00",
      end_time: "17:30:00",
      location: "関東",
      description: "中級ヨガレッスン",
      imagePath: "/images/lesson14.jpg",
      moviePath: "/movies/lesson14.mp4",
      review: 5,
      indicator: 85.0,
      momentum: 110,
    },
    {
      id: 15,
      store_id: 3,
      date: "2024-12-15",
      start_time: "08:00:00",
      end_time: "09:30:00",
      location: "関西",
      description: "朝のリフレッシュ瞑想",
      imagePath: "/images/lesson15.jpg",
      moviePath: "/movies/lesson15.mp4",
      review: 5,
      indicator: 92.5,
      momentum: 120,
    },
    {
      id: 16,
      store_id: 1,
      date: "2024-12-16",
      start_time: "19:00:00",
      end_time: "20:30:00",
      location: "関東",
      description: "夜ヨガセッション",
      imagePath: "/images/lesson16.jpg",
      moviePath: "/movies/lesson16.mp4",
      review: null,
      indicator: 87.1,
      momentum: null,
    },
    {
      id: 17,
      store_id: 2,
      date: "2024-12-17",
      start_time: "17:00:00",
      end_time: "18:30:00",
      location: "関西",
      description: "夜のピラティス",
      imagePath: "/images/lesson17.jpg",
      moviePath: "/movies/lesson17.mp4",
      review: 4,
      indicator: 80.0,
      momentum: 100,
    },
    {
      id: 18,
      store_id: 3,
      date: "2024-12-18",
      start_time: "12:00:00",
      end_time: "13:30:00",
      location: "関西",
      description: "ランチタイムヨガ",
      imagePath: "/images/lesson18.jpg",
      moviePath: "/movies/lesson18.mp4",
      review: 3,
      indicator: 75.0,
      momentum: 70,
    },
    {
      id: 19,
      store_id: 1,
      date: "2024-12-19",
      start_time: "10:00:00",
      end_time: "11:30:00",
      location: "関東",
      description: "初心者向けリラックスヨガ",
      imagePath: "/images/lesson19.jpg",
      moviePath: "/movies/lesson19.mp4",
      review: 5,
      indicator: 90.5,
      momentum: 125,
    },
    {
      id: 20,
      store_id: 2,
      date: "2024-12-20",
      start_time: "13:00:00",
      end_time: "14:30:00",
      location: "関西",
      description: "中級ピラティスレッスン",
      imagePath: "/images/lesson20.jpg",
      moviePath: "/movies/lesson20.mp4",
      review: null,
      indicator: 82.0,
      momentum: 85,
    },
  ]);
  await knex.raw("select setval(pg_get_serial_sequence('lesson', 'id'), MAX(id)) FROM lesson");
};
